### ISSUE TITLE
About inconsistent depth scale for unproject

### ISSUE THREAD

**Issue by lingxin12** [cvg/depthsplat#33]
hello, i use the point cloud returned by the encoder (input 2 views), but the point cloud are generated in the front of 2 views respectively.

![total](https://github.com/user-attachments/assets/d726a7ac-fcc7-4d1a-8a84-e7ee168b2182)
![cam0](https://github.com/user-attachments/assets/565b3016-239e-42b5-ba9f-63b4f5b3cb32)
![cam1](https://github.com/user-attachments/assets/77aa7ee3-1142-45c4-8498-bcceeb453c42)

So, how can i do to ensure consistent point cloud generation for 2 input views.

**Comment by haofeixu** [comment]
Hi, thank you for your question. Could you let me know which dataset are you using? I am happy to look into this issue if you could share more information of this sample (e.g., dataset, scene name, input view indices), thanks.

**Comment by lingxin12** [comment]
> Hi, thank you for your question. Could you let me know which dataset are you using? I am happy to look into this issue if you could share more information of this sample (e.g., dataset, scene name, input view indices), thanks.

Yes, i use another dataset (it is hypernerf/virg/broom2) and input left and right view on frame 0 respectively, and i use the predicted depth from encoder to unproject. 

Meanwhile, i noticed that the predicted depth did not match the range of real scene because the predicted depth is so small. How can i do to expand the range of predicted depth and gaussians scale.

**Comment by haofeixu** [comment]
Thank you for the information. I guess our model might not work seamlessly out-of-the-box in this setup, since there are several differences:
- It seems that you are using a rectified stereo pair as input to our model, while our depth model is designed and trained to take unrectified posed images as input. If you are interested in rectified stereo depth estimation, you can consider to modify our model to predict disparity with stereo matching (for example https://github.com/autonomousvision/unimatch/blob/master/unimatch/unimatch.py#L207), and then convert disparity to depth with camera parameters. This would also give you more reliable depth predictions when rectified stereo pairs are available.
- The hypernerf dataset seems to contain dynamic objects, while our current model assumes static scenes. Some adaptions of our model would be necessary to make it work on dynamic scenes.
- The image format (portrait orientation) of the hypernerf dataset is different from our training data (landscape orientation), an additional fine-tuning on this dataset would be beneficial to achieve more reliable results.

The depth range is controlled with the `near` and `far` parameters (https://github.com/cvg/depthsplat/blob/main/config/experiment/dl3dv.yaml#L40-L41), by default we use 1-200 for outdoor scenes, you can try to adjust them accordingly on your dataset.

**Comment by lingxin12** [comment]
> Thank you for the information. I guess our model might not work seamlessly out-of-the-box in this setup, since there are several differences:
> 
> * It seems that you are using a rectified stereo pair as input to our model, while our depth model is designed and trained to take unrectified posed images as input. If you are interested in rectified stereo depth estimation, you can consider to modify our model to predict disparity with stereo matching (for example https://github.com/autonomousvision/unimatch/blob/master/unimatch/unimatch.py#L207), and then convert disparity to depth with camera parameters. This would also give you more reliable depth predictions when rectified stereo pairs are available.
> * The hypernerf dataset seems to contain dynamic objects, while our current model assumes static scenes. Some adaptions of our model would be necessary to make it work on dynamic scenes.
> * The image format (portrait orientation) of the hypernerf dataset is different from our training data (landscape orientation), an additional fine-tuning on this dataset would be beneficial to achieve more reliable results.
> 
> The depth range is controlled with the `near` and `far` parameters (https://github.com/cvg/depthsplat/blob/main/config/experiment/dl3dv.yaml#L40-L41), by default we use 1-200 for outdoor scenes, you can try to adjust them accordingly on your dataset.

Thanks for you reply, i will try it.
