### ISSUE TITLE
How to get the Gaussian visualization in the demo?

### ISSUE THREAD

**Issue by yifliu3** [cvg/depthsplat#6]
Hi! The demo results are truly remarkable, and I was thoroughly impressed by the quality of the reconstructions.

I'm particularly interested in the 3D Gaussian primitives used in your method. Is there a way to visualize these reconstructed Gaussians?

**Comment by LiHaodong0217** [comment]
you can use any viewer to visualize 3dgs render result which support to render 3dgs.
maybe you can try it:https://jatentaki.github.io/assets/gaussianviewer/index.html

**Comment by CanCanZeng** [comment]
Hi @LiHaodong0217 @yifliu3 , I also interested in this project and I'd like to ask how to save the gaussians in gaussian_splatting format (ply point cloud file)?

**Comment by haofeixu** [comment]
Hi, you can try to use this code https://github.com/donydchen/mvsplat/blob/main/src/paper/generate_point_cloud_figure_mvsplat.py to visualize the 3D Gaussians. 
It would take a bit of time for me to clean my code due to the project deadlines, thank you for your patience.

**Comment by CanCanZeng** [comment]
I found an `export_ply` function, but it requires inputs of **scales** and **rotations**, and depthsplat only outputs **covariance** in the `Gaussians` class. I couldn't find a function that converts **covariance** to **scales** and **rotations**. Why predict **covariance** directly instead of **scales** and **rotations**?
